/**
 * FOURFOLD -- game rules.
 *
 * A claim is a set of cells. A cell in the claim scores only if its mirror
 * partner across some median is ALSO in the claim, and the two charges are
 * coherent (both in {gold, purple}, or both in {blue, red} -- i.e. the same
 * coset of the subgroup H fixing sqrt6).
 *
 * The whole game turns on one asymmetry, verified exhaustively at depths
 * 2..6 against the reference implementation:
 *
 *   across m_A  every cell is coherent            (Theorem 3: the mirror
 *                                                  lifts to an automorphism)
 *   across m_B  exactly the cells whose first
 *               non-X digit is B, plus the hub    ((4^d - 1)/3 + 1 cells)
 *   across m_C  exactly the cells whose first
 *               non-X digit is C, plus the hub
 *
 * So the vertical axis is free and the two diagonals are earned. A player
 * who works out that only the FIRST NON-CENTRE DIGIT of an address decides
 * the diagonal axes has found the same obstruction that stops the figure
 * from having 120-degree symmetry.
 */

import {
  AXES,
  buildFigure,
  coherent,
  type Axis,
  type Cell,
  type Charge,
  type Figure,
} from "./figure";
import {
  makeIdentifier,
  type ClaimReport,
  type SiteVerdict,
} from "./identify";

/**
 * Points per cell per satisfied axis. The vertical median is worth least
 * because it always works; the diagonals are worth more because only a
 * third of the board can use them.
 */
export const AXIS_VALUE: Record<Axis, number> = { A: 1, B: 3, C: 3 };

/** A claim needs at least this many scoring cells to stand. */
export const MIN_CLAIM = 3;

/**
 * ...and at most this many cells selected.
 *
 * The cap is not arbitrary flavour, it closes a hole. Because m_A is an
 * EXACT symmetry, every cell on the board is coherent across it -- so a
 * selection of the whole board has every cell paired, scores 772 points at
 * depth 4, claims every cell, and ends the game on turn one. The property
 * that makes the figure interesting is also the property that lets a player
 * sweep it.
 *
 * A symmetry in the sense this game means is a *motif*: the orbit of a cell
 * under the group generated by the three median reflections has at most six
 * elements, so twelve leaves room for a compound figure while making a
 * board-sweep impossible.
 */
export const MAX_CLAIM = 12;

export type PlayerId = 0 | 1;

export type CellVerdict = SiteVerdict<Axis>;
export type ClaimAnalysis = ClaimReport<Axis>;

/**
 * The game is one configuration of the extracted identifier: the three
 * medians as axes, H-coset membership as coherence, and the 1/3/3 weighting
 * that prices the vertical median cheapest because -- in this convention --
 * it always works.
 */
const identify = makeIdentifier<Axis, Charge>({
  axes: AXES,
  coherent,
  axisValue: AXIS_VALUE,
  minClaim: MIN_CLAIM,
  maxClaim: MAX_CLAIM,
});

/**
 * Score a candidate claim. Pure -- takes the selection, returns the verdict
 * without touching game state, so the UI can show a live preview.
 */
export function analyseClaim(
  figure: Figure,
  selection: ReadonlySet<number>
): ClaimAnalysis {
  return identify(figure.cells, selection);
}

export interface LogEntry {
  player: PlayerId;
  kind: "claim" | "pass";
  points: number;
  cells: number;
  axes: Axis[];
}

export interface GameState {
  figure: Figure;
  /** Owner per cell index, or null if unclaimed. */
  owner: (PlayerId | null)[];
  scores: [number, number];
  turn: PlayerId;
  selection: ReadonlySet<number>;
  /** Consecutive passes; two in a row ends the game. */
  passes: number;
  over: boolean;
  log: LogEntry[];
}

export function newGame(depth: number): GameState {
  const figure = buildFigure(depth);
  return {
    figure,
    owner: new Array(figure.cells.length).fill(null),
    scores: [0, 0],
    turn: 0,
    selection: new Set(),
    passes: 0,
    over: false,
    log: [],
  };
}

export function toggleCell(state: GameState, i: number): GameState {
  if (state.over || state.owner[i] !== null) return state;
  const next = new Set(state.selection);
  if (next.has(i)) {
    next.delete(i);
  } else {
    // Deselecting is always allowed; only growing past the cap is refused.
    if (next.size >= MAX_CLAIM) return state;
    next.add(i);
  }
  return { ...state, selection: next };
}

export function clearSelection(state: GameState): GameState {
  return { ...state, selection: new Set() };
}

/** Commit the current selection as a claim, if it stands. */
export function submitClaim(state: GameState): GameState {
  if (state.over) return state;
  const analysis = analyseClaim(state.figure, state.selection);
  if (!analysis.valid) return state;

  const owner = state.owner.slice();
  for (const i of analysis.verdicts.keys()) owner[i] = state.turn;
  // Cells that scored nothing are released back to the board.

  const scores: [number, number] = [...state.scores];
  scores[state.turn] += analysis.points;

  const log: LogEntry[] = [
    ...state.log,
    {
      player: state.turn,
      kind: "claim",
      points: analysis.points,
      cells: analysis.verdicts.size,
      axes: analysis.axes,
    },
  ];

  const remaining = owner.some((o) => o === null);
  return {
    ...state,
    owner,
    scores,
    log,
    selection: new Set(),
    passes: 0,
    turn: (1 - state.turn) as PlayerId,
    over: !remaining,
  };
}

export function pass(state: GameState): GameState {
  if (state.over) return state;
  const passes = state.passes + 1;
  return {
    ...state,
    selection: new Set(),
    passes,
    over: passes >= 2,
    turn: (1 - state.turn) as PlayerId,
    log: [
      ...state.log,
      { player: state.turn, kind: "pass", points: 0, cells: 0, axes: [] },
    ],
  };
}

export function winner(state: GameState): PlayerId | "draw" | null {
  if (!state.over) return null;
  if (state.scores[0] === state.scores[1]) return "draw";
  return state.scores[0] > state.scores[1] ? 0 : 1;
}

/**
 * Cells whose partner across `axis` is coherent -- the set a player can
 * profitably use on that axis. Used by the board's axis filter.
 */
export function coherentOn(figure: Figure, axis: Axis): Set<number> {
  const out = new Set<number>();
  for (const c of figure.cells) if (c.coherentAxes.includes(axis)) out.add(c.i);
  return out;
}

/** Convenience for the ledger: how many cells each axis can reach. */
export function axisCapacity(figure: Figure): Record<Axis, number> {
  const out = { A: 0, B: 0, C: 0 } as Record<Axis, number>;
  for (const c of figure.cells) for (const ax of c.coherentAxes) out[ax] += 1;
  return out;
}

export type { Cell, Figure };
